#Change depending on device (use absolute paths)
data_dir: "/home/rohanshah/data/cmip6/1.40625_npz"
mask2former_dir: "/home/rohanshah/Mask2Former"
default_root_dir: "/home/rohanshah/climate-learn/results_pretrained_cmip6_stage2/"
ckpt_dir: "/home/rohanshah/climate-learn/results_pretrained_cmip6_stage1/"
gpu: [0,1,2,3,4,5,6,7]
#use gradient accumulation to maintain a fixed batch size across devices
batch_size: 8
grad_acc: 1
#####################

#Switch between scratch and pretrained models
use_pretrained_weights: True
#Switch between video and image segmentation weights
pretrained_weights: 'video'

in_variables: [
  "land_sea_mask",
  "orography",
  "lattitude",
  "2m_temperature",
  "geopotential_50",
  "geopotential_250",
  "geopotential_500",
  "geopotential_600",
  "geopotential_700",
  "geopotential_850",
  "geopotential_925",
  "u_component_of_wind_50",
  "u_component_of_wind_250",
  "u_component_of_wind_500",
  "u_component_of_wind_600",
  "u_component_of_wind_700",
  "u_component_of_wind_850",
  "u_component_of_wind_925",
  "v_component_of_wind_50",
  "v_component_of_wind_250",
  "v_component_of_wind_500",
  "v_component_of_wind_600",
  "v_component_of_wind_700",
  "v_component_of_wind_850",
  "v_component_of_wind_925",
  "temperature_50",
  "temperature_250",
  "temperature_500",
  "temperature_600",
  "temperature_700",
  "temperature_850",
  "temperature_925",
  "specific_humidity_50",
  "specific_humidity_250",
  "specific_humidity_500",
  "specific_humidity_600",
  "specific_humidity_700",
  "specific_humidity_850",
  "specific_humidity_925",
]
out_variables: ["2m_temperature", "geopotential_500", "temperature_850"]
constants: ["land_sea_mask", "orography", "lattitude"]
subsample: 1
history: 1
window: 0
num_workers: 1

model: 'mask2former'

in_img_size: [512, 512]
embed_type: 'climax'
mlp_embed_depth: 1
decoder_depth: 2
patch_size: 4
embed_dim: 192
out_embed_dim: 256
freeze_backbone: False
freeze_embeddings: False
embed_norm: True
continuous_model: True
min_pred_range: 1
max_pred_range: 28
hrs_each_step: 6
fixed_lead_time_eval: 72

stage: 2
num_epochs: 50
warmup_epochs: 5
patience: 5
val_every_n_steps: 2000
lr: 5.0e-4
warmup_start_lr: 1.0e-8
eta_min: 1.0e-8
betas: [0.9, 0.95]
weight_decay: 1.0e-5
seed: 42