#Change depending on device
data_dir: "/eagle/MDClimSim/tungnd/data/CMIP6/MPI-ESM/1.40625deg_np_10_shards/"
default_root_dir: "/eagle/MDClimSim/tungnd/climate-learn/results_cmip6_stage2/"
ckpt_dir: "/eagle/MDClimSim/tungnd/climate-learn/results_cmip6_stage1/"
gpu: 4
batch_size: 2
grad_acc: 1
#####################

#Switch between scratch and pretrained models
use_pretrained_weights: True
pretrained_weights: 'dinov2_vitl14'
# pretrained_weights: 'openai/clip-vit-large-patch14'
# pretrained_weights: 'nasa'
#Switch between normal and climax embeddings
embed_type: 'climax'

### Data

in_variables: [
  # "land_sea_mask",
  # "orography",
  # "lattitude",
  "2m_temperature",
  "10m_u_component_of_wind", 
  "10m_v_component_of_wind",
  "geopotential_50",
  "geopotential_250",
  "geopotential_500",
  "geopotential_600",
  "geopotential_700",
  "geopotential_850",
  "geopotential_925",
  "u_component_of_wind_50",
  "u_component_of_wind_250",
  "u_component_of_wind_500",
  "u_component_of_wind_600",
  "u_component_of_wind_700",
  "u_component_of_wind_850",
  "u_component_of_wind_925",
  "v_component_of_wind_50",
  "v_component_of_wind_250",
  "v_component_of_wind_500",
  "v_component_of_wind_600",
  "v_component_of_wind_700",
  "v_component_of_wind_850",
  "v_component_of_wind_925",
  "temperature_50",
  "temperature_250",
  "temperature_500",
  "temperature_600",
  "temperature_700",
  "temperature_850",
  "temperature_925",
  "specific_humidity_50",
  "specific_humidity_250",
  "specific_humidity_500",
  "specific_humidity_600",
  "specific_humidity_700",
  "specific_humidity_850",
  "specific_humidity_925",
]
out_variables: ["2m_temperature", "geopotential_500", "temperature_850"]
# constants: ["land_sea_mask", "orography", "lattitude"]
min_pred_range: 1
max_pred_range: 28
hrs_each_step: 6
fixed_lead_time_eval: 72
subsample: 1
history: 1
window: 0
num_workers: 1

### Model

model: 'vit_pretrained'

in_img_size: [128, 256]
patch_size: 4
embed_norm: True
mlp_embed_depth: 1
decoder_depth: 2
freeze_backbone: False
freeze_embeddings: False
continuous_model: True

stage: 2
num_epochs: 50
warmup_epochs: 5
patience: 5
val_every_n_steps: 2000
lr: 5.0e-4
warmup_start_lr: 1.0e-8
eta_min: 1.0e-8
betas: [0.9, 0.95]
weight_decay: 1.0e-5
seed: 42