# data_dir: "/home/data/datasets/cmip6/5.625deg_npz_corrected/"
data_dir: "/local2/hbansal/cmip6/5.625deg_npz_corrected/"
in_variables: [
  "land_sea_mask",
  "orography",
  "lattitude",
  "2m_temperature",
  "geopotential_50",
  "geopotential_250",
  "geopotential_500",
  "geopotential_600",
  "geopotential_700",
  "geopotential_850",
  "geopotential_925",
  "u_component_of_wind_50",
  "u_component_of_wind_250",
  "u_component_of_wind_500",
  "u_component_of_wind_600",
  "u_component_of_wind_700",
  "u_component_of_wind_850",
  "u_component_of_wind_925",
  "v_component_of_wind_50",
  "v_component_of_wind_250",
  "v_component_of_wind_500",
  "v_component_of_wind_600",
  "v_component_of_wind_700",
  "v_component_of_wind_850",
  "v_component_of_wind_925",
  "temperature_50",
  "temperature_250",
  "temperature_500",
  "temperature_600",
  "temperature_700",
  "temperature_850",
  "temperature_925",
  "specific_humidity_50",
  "specific_humidity_250",
  "specific_humidity_500",
  "specific_humidity_600",
  "specific_humidity_700",
  "specific_humidity_850",
  "specific_humidity_925",
]
out_variables: ["2m_temperature", "geopotential_500", "temperature_850"]
constants: ["land_sea_mask", "orography", "lattitude"]
train_years: [1850, 2011]
val_years: [2011, 2013]
test_years: [2013, 2015]
min_pred_range: 1
max_pred_range: 28
hrs_each_step: 6
subsample: 1
history: 1
window: 0
num_workers: 1
fixed_lead_time_eval: 72

model: 'mask2former'

in_img_size: [512, 512]
embed_type: 'climax'
mlp_embed_depth: 1
decoder_depth: 1
use_pretrained_weights: True
freeze_backbone: False
freeze_embeddings: False
continuous_model: True
patch_size: 4
embed_dim: 192
out_embed_dim: 256
embed_norm: True

batch_size: 4
patience: 5
num_epochs: 50
gpu: [0]
seed: 42
lr: 5.0e-4
warmup_epochs: 5
max_epochs: 50
warmup_start_lr: 1.0e-8
eta_min: 1.0e-8
weight_decay: 1.0e-5
betas: [0.9, 0.95]
val_every_n_steps: 1000