dataset: 'era5'
data_dir: "/local2/hbansal/era5/5.625deg_npz/"
# data_dir: "/data0/datasets/weatherbench/data/weatherbench/era5/5.625deg_npz/"
in_variables: [
          "2m_temperature",
        #   "10m_u_component_of_wind",
        #   "10m_v_component_of_wind",
        #   "toa_incident_solar_radiation",
          "geopotential_50",
          "geopotential_250",
          "geopotential_500",
          "geopotential_600",
          "geopotential_700",
          "geopotential_850",
          "geopotential_925",
          "u_component_of_wind_50",
          "u_component_of_wind_250",
          "u_component_of_wind_500",
          "u_component_of_wind_600",
          "u_component_of_wind_700",
          "u_component_of_wind_850",
          "u_component_of_wind_925",
          "v_component_of_wind_50",
          "v_component_of_wind_250",
          "v_component_of_wind_500",
          "v_component_of_wind_600",
          "v_component_of_wind_700",
          "v_component_of_wind_850",
          "v_component_of_wind_925",
          "temperature_50",
          "temperature_250",
          "temperature_500",
          "temperature_600",
          "temperature_700",
          "temperature_850",
          "temperature_925",
          "specific_humidity_50",
          "specific_humidity_250",
          "specific_humidity_500",
          "specific_humidity_600",
          "specific_humidity_700",
          "specific_humidity_850",
          "specific_humidity_925",
        #   "relative_humidity_50",
        #   "relative_humidity_250",
        #   "relative_humidity_500",
        #   "relative_humidity_600",
        #   "relative_humidity_700",
        #   "relative_humidity_850",
        #   "relative_humidity_925",
    ]
# in_variables: ["geopotential_500"]
# in_variables: ["2m_temperature", "geopotential_500", "temperature_850"]
out_variables: ["2m_temperature", "geopotential_500", "temperature_850"]
# out_variables: ["geopotential_500"]
constants: ["land_sea_mask", "orography", "lattitude"]
# constants: []
train_years: [1979, 2016]
val_years: [2016, 2017]
test_years: [2017, 2019]
pred_range: 72
subsample: 1
history: 3
window: 6
num_workers: 1

#MODEL
model: 'resnet'
hidden_channels: 128
activation: 'leaky'
norm: True
dropout: 0.1
n_blocks: 28
use_pretrained_weights: False


#OPTIMIZATION
batch_size: 128
lr: 5.0e-7
weight_decay: 1.0e-5
betas: [0.9, 0.99]
warmup_epochs: 5
num_epochs: 50
warmup_start_lr: 1.0e-8
eta_min: 1.0e-8
patience: 5
val_every_n_steps: 500
seed: 42

#GPU!!!!
gpu: 2
ckpt: 'jwv8xrn5'
# ckpt: null