dataset: "cmip6"
data_dir: "/local2/hbansal/cmip6/5.625deg_npz_corrected/"
# data_dir: "/data0/datasets/weatherbench/data/esgf/cmip6/5.625deg_npz_corrected/"
in_variables: [
          "2m_temperature",
          "geopotential_50",
          "geopotential_250",
          "geopotential_500",
          "geopotential_600",
          "geopotential_700",
          "geopotential_850",
          "geopotential_925",
          "u_component_of_wind_50",
          "u_component_of_wind_250",
          "u_component_of_wind_500",
          "u_component_of_wind_600",
          "u_component_of_wind_700",
          "u_component_of_wind_850",
          "u_component_of_wind_925",
          "v_component_of_wind_50",
          "v_component_of_wind_250",
          "v_component_of_wind_500",
          "v_component_of_wind_600",
          "v_component_of_wind_700",
          "v_component_of_wind_850",
          "v_component_of_wind_925",
          "temperature_50",
          "temperature_250",
          "temperature_500",
          "temperature_600",
          "temperature_700",
          "temperature_850",
          "temperature_925",
          "specific_humidity_50",
          "specific_humidity_250",
          "specific_humidity_500",
          "specific_humidity_600",
          "specific_humidity_700",
          "specific_humidity_850",
          "specific_humidity_925",
    ]
# in_variables: ["geopotential_500"]
# in_variables: ["2m_temperature", "geopotential_500", "temperature_850"]
out_variables: ["2m_temperature", "geopotential_500", "temperature_850"]
# out_variables: ["geopotential_500"]
constants: ["land_sea_mask", "orography", "lattitude"]
# constants: []
train_years: [1850, 2011]
val_years: [2011, 2013]
test_years: [2013, 2015]
pred_range: 72
subsample: 1
history: 3
window: 6
num_workers: 1

#MODEL
model: 'resnet'
hidden_channels: 128
activation: 'leaky'
norm: True
dropout: 0.1
n_blocks: 28
use_pretrained_weights: False


#OPTIMIZATION
batch_size: 128
lr: 5.0e-4
weight_decay: 1.0e-5
betas: [0.9, 0.99]
warmup_epochs: 5
num_epochs: 50
warmup_start_lr: 1.0e-8
eta_min: 1.0e-8
patience: 5
val_every_n_steps: 500
seed: 42

#GPU!!!!
gpu: 5
ckpt: 'jwv8xrn5'