from .climatology import Climatology
from .interpolation import Interpolation
from .linear_regression import LinearRegression
from .persistence import Persistence
from .resnet import ResNet
from .unet import Unet
from .utils import MODEL_REGISTRY
from .vit import VisionTransformer
from .vit_pretrained import ViTPretrained
from .resnet_pretrained import ResNetPretrained
from .swin_pretrained import SwinPretrained